[package]
name = "feather-index"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
clap-verbosity-flag = "3.0.3"
color-eyre = "0.6.5"
tokio = { version = "1", features = ["full"] }
tracing-log = "0.2.0"
tracing-subscriber = "0.3.19"
